# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "Build the Ionic App"
private_lane :build_ionic do |options|
    if options[:bump]
        sh("npm", "run", "bump:build:version")
    else
        sh("npm", "run", "bump:build")
    end
    ionic(
        platform: lane_context[SharedValues::PLATFORM_NAME].to_s,
        prod: (options[:prod] ? true : false),
        keystore_path: '../../../electric-certs/google_play/electric-release.keystore',
        keystore_alias: 'electric-charger',
        keystore_password: ENV["ELECTRIC_KEYSTORE_PWD"]
    )
end

platform :android do
#  desc "Runs all the tests"
#  lane :test do
#    gradle(task: "test")
#  end

  desc "Deploy a new beta version"
  lane :alpha do
    build_ionic
    gradle(task: "clean assembleRelease", project_dir: './platforms/android')
    upload_to_play_store(track: 'alpha')
  end

  desc "Deploy a new version to the Google Play"
  lane :prod do
    build_ionic(prod: true)
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
