# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "Build the Ionic App"
private_lane :build_ionic do |options|
    if options[:bump]
        sh("npm", "run", "bump:build:version")
    else
        sh("npm", "run", "bump:build")
    end
    sh("npm", "run", "copy:version")
    keychain_entry = CredentialsManager::AccountManager.new(user: "electric")
    password = keychain_entry.password
    ionic(
        platform: lane_context[SharedValues::PLATFORM_NAME].to_s,
        prod: (options[:prod] ? true : false),
        keystore_path: '../../../electric-certs/google_play/electric-release.keystore',
        keystore_alias: 'electric-charger',
        keystore_password: password
    )
end

platform :ios do
  desc "Just build the thing"
  lane :dev do
    build_ionic
    match(type: "appstore", readonly: true)
    build_app(
        export_method: "app-store",
        export_options: {
            provisioningProfiles: {
                "com.electric.icharger.app" => "match Development com.electric.icharger.app"
            }
        }
    )
  end

  lane :frames do
    frame_screenshots(path: "./fastlane/screenshots")
  end

  lane :screenshots do
    capture_screenshots
    frames
    upload_to_app_store
  end

  lane :alpha do
    build_ionic(prod: true)
    match(type: "appstore", readonly: true)
    build_app(
        export_method: "app-store",
        export_options: {
            provisioningProfiles: {
                "com.electric.icharger.app" => "match AppStore com.electric.icharger.app"
            }
        }
    )
    upload_to_testflight
  end

  lane :prod do
    build_ionic(prod: true, bump: true)
    match(type: "appstore", readonly: true)
    build_app(
        export_method: "app-store",
        export_options: {
            provisioningProfiles: {
                "com.electric.icharger.app" => "match AppStore com.electric.icharger.app"
            }
        }
    )

    # Yet to add 'deliver' to this
  end
end


platform :android do
#  desc "Runs all the tests"
#  lane :test do
#    gradle(task: "test")
#  end

  desc "Deploy a new internal version"
  lane :internal do
    build_ionic
    gradle(task: "clean assembleRelease", project_dir: './platforms/android')
    upload_to_play_store(track: 'internal')
  end

  desc "Deploy a new beta version"
  lane :beta do
    build_ionic(prod: true)
    gradle(task: "clean assembleRelease", project_dir: './platforms/android')
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :prod do
    build_ionic(prod: true)
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
