#!/usr/bin/env bash

. /opt/wireless/scripts/functions.sh
. /opt/wireless/config/wlan.conf

# Allow override
if [ -f "/root/.wlan.conf" ]; then
    echo "Using values from /root/.wlan.conf..."
    source "/root/.wlan.conf"
fi

# quit if we're called for the loopback
if [ "$IFACE" = lo ]; then
    exit 0
fi

add_wlan1_if_not_there

# Enable IP forwarding and masq.
#echo 1 >/proc/sys/net/ipv4/ip_forward

# Cannot check for the actual channel until its connected.
# So this script is run in /etc/network

# Make sure the channel number is the same
WLAN0_CHANNEL=$(iwlist channel 2>/dev/null | grep Current | grep 'Current' | gawk '{print gensub(/\(Channel ([0-9]+)\)/, "\\1", "g");  }' | awk '{print $4}')
if [ "${WLAN0_CHANNEL}x" = "x" ]; then
    echo "It doesn't look like wlan0 is connected to anything... default to a sane default (11)"
    WLAN0_CHANNEL=11
else
    echo "found wlan0, its on channel $WLAN0_CHANNEL"
fi

# Check iw wlan0 link, and make sure "Connected to" is there.
# Only then can we find the channel and adjust hostapd config.

# Find existing channel number in the hostapd.config

# EXISTING_CHANNEL=99
# EXISTING_NAME=Electric
# if [ -f /etc/hostapd/hostapd.conf ]; then
#     EXISTING_CHANNEL=$(cat /etc/hostapd/hostapd.conf  | grep channel | awk -F= '{print $2}')
#     EXISTING_NAME=$(cat /etc/hostapd/hostapd.conf  | grep ssid | head -1 | awk -F= '{print $2}')
# fi

# if [ "$EXISTING_CHANNEL" != "$WLAN0_CHANNEL" ] || [ "$EXISTING_NAME" != "${WLAN1_NAME}" ] ; then
#     echo "Changing hostapd channel to $WLAN0_CHANNEL..."
#     echo "WLAN1 name will be: ${WLAN1_NAME}"

#     hostapd_template_str=$(cat /etc/hostapd/hostapd.conf.template)
#     eval "echo >/etc/hostapd/hostapd.conf \"${hostapd_template_str}\""
# fi

check_firewall_forwarding_rules

# this has to happen.
# The startup of wlan0 may change the channel of wlan0...
# This affects hostapd, which won't "come back" unless it is restarted

echo "Restarting hostapd..."
/etc/init.d/hostapd restart

echo "Restarting dnsmasq..."
/etc/init.d/dnsmasq restart

exit 0
