#!/usr/bin/env bash

# quit if we're called for the loopback
if [ "$IFACE" = lo ]; then
    exit 0
fi

echo "Stopping services we no longer need"

echo "Restarting hostapd..."
/etc/init.d/hostapd stop

echo "Restarting dnsmasq..."
/etc/init.d/dnsmasq stop

exit 0
